### PR TITLE
fix test > pkg-test symlink

### PR DESCRIPTION
**Pull request by jhheider**
ref https://github.com/teaxyz/pantry.core/actions/runs/4159431080/jobs/7195515499

### CODE REVIEW

**Comment by jhheider** [comment]
I'd love to wait on review, but this is too risky (no tests are running on new builds). If I've made a mistake, we can revert.

**Comment by mxcl** [comment]
you could also have changed the workflows to use `pkg test`. I added the symlinks as a temporary measure.

**Comment by mxcl** [comment]
apologies though. this was a basic error 🤦🏻‍♂️

**Comment by jhheider** [comment]
Yeah, I figured we'll update the workflows, but this needed fixing anyway.

**Pull request merged**
