### PR TITLE
add `bk` shim for `pkg` so we can provide via pantry

### PR DESCRIPTION
**Pull request by jhheider**

### CODE REVIEW

**Comment by mxcl** [comment]
so… sure

but I was considering `tea pkg` working by having a kind of provides that is “this exists but shouldn't be accessible via magic”.

Although maybe that's dumb. Though we still could special case `tea pkg` in tea/cli itself.

But this doesn't hurt for now.

**Comment by mxcl** [comment]
I went to bump but I see you have a pre-release in there, so leaving to you

**Comment by jhheider** [comment]
Hrm. I shouldn't.

**Comment by jhheider** [comment]
My rationale is that `pkg` might be too generic to provide via magic, but something like `bk` would require you to *mean* it.

**Pull request merged**
