### PR TITLE
fix var quoting in `cc`

### LINKED ISSUE #289: missing shellchecks in `cc`
```
FAILED: thumbnailer/gdk-pixbuf-thumbnailer.p/gnome-thumbnailer-skeleton.c.o 
cc -Ithumbnailer/gdk-pixbuf-thumbnailer.p -Ithumbnailer -I../thumbnailer -I. -I.. -Igdk-pixbuf -I/opt/pcre.org/v2/v10.42.0/lib/pkgconfig/../../include -I/opt/gnome.org/glib/v2.79.1/lib/pkgconfig/../../include/glib-2.0 -I/opt/gnome.org/glib/v2.79.1/lib/pkgconfig/../../lib/glib-2.0/include -I/opt/gnome.org/glib/v2.79.1/lib/pkgconfig/../../../../../gnu.org/gettext/v0/include -I/opt/sourceware.org/libffi/v3.4.4/lib/pkgconfig/../../include -I/opt/gnome.org/glib/v2.79.1/lib/pkgconfig/../../include -I/opt/zlib.net/v1.3.1/lib/pkgconfig/../../include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O3 -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=700 -DHAVE_CONFIG_H=1 -fPIC -pthread -Wpointer-arith -Wformat=2 -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wcast-align -Wmissing-noreturn -Wmissing-format-attribute -fno-strict-aliasing -Wno-int-conversion -Wno-uninitialized -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=empty-body -fvisibility=hidden -DTHUMBNAILER_RETURNS_PIXBUF '-DTHUMBNAILER_USAGE="Thumbnail images"' -MD -MQ thumbnailer/gdk-pixbuf-thumbnailer.p/gnome-thumbnailer-skeleton.c.o -MF thumbnailer/gdk-pixbuf-thumbnailer.p/gnome-thumbnailer-skeleton.c.o.d -o thumbnailer/gdk-pixbuf-thumbnailer.p/gnome-thumbnailer-skeleton.c.o -c ../thumbnailer/gnome-thumbnailer-skeleton.c
/__w/_actions/pkgxdev/brewkit/v1/share/toolchain/bin/cc: line 25: [: too many arguments
```

https://github.com/pkgxdev/pantry/actions/runs/7656908213/job/20866359210

### PR DESCRIPTION
**Pull request by jhheider**
closes #289

### CODE REVIEW

**Comment by mxcl** [comment]
Just so I don't repeat this, what is the issue exactly? I went to the ticket but don’t get it.

**Comment by jhheider** [comment]
`cc: line 25: [: too many arguments`

resulting from 

`'-DTHUMBNAILER_USAGE="Thumbnail images"'`

on line

`    if [ $arg != -Werror ]; then`

https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck highlights them all, if you want quick visibility

**Comment by mxcl** [comment]
k, right. Always quote args that may contain quotes. Got it. I guess always quote for safety but I just don't like it.

**Comment by jhheider** [comment]
and of such dislike are new shells born

**Pull request merged**
