### PR TITLE
cleanup test dir on github-action runners

### PR DESCRIPTION
**Pull request by jhheider**
will prevent OoS in the future

### CODE REVIEW

**Comment by mxcl** [comment]
brewkit is a general purpose toolkit not specific to us. Does it have to go here?

**Comment by jhheider** [comment]
It doesn't; felt natural to me, since we have GHA-specific code there, and trapping it ensures it happens. Otherwise, we'll need to either emit the build/test directories in GHA on failure (is that possible?) and `always()` remove them, or just clean all 8-character directories from $TMPDIR at the end.

**Comment by jhheider** [comment]
I guess we can spit them into the `$GITHUB_ENV` early on, and they should be present even on failure.

**Comment by jhheider** [comment]
If that's better, we can do that. Otherwise, we can just sanitize the tmp root less discriminately in the build.yml

**Comment by mxcl** [comment]
It can go in the `.github` code. It cannot go in brewkit itself.

The only GHA specific code we have in brewkit itself is to change output format for GHA which is general code for anyone. You are adding code specific to tea’s runners which I would really prefer not to have at all.

In fact this is code that cleans up the TMP_DIR, please run a service on the runner that does that! Do not add code to our generalized infrastructure for your specific needs.

**Comment by mxcl** [comment]
Reopening as I was first thing in morning grumpy.

However I really do want to keep “hacks for tea’s specific infra” out of the “kit” and preferably out of all of it since I want these actions to be generalized for everyone one day too (so anyone can make builds compatible with tea).

**Comment by jhheider** [comment]
Cleaning the TMP_DIR indiscriminately (probably with `find $TMP_DIR -type d -mindepth 1 -maxdepth 1 -mtime +1 -name '????????' -exec rm -rf {} \;`) is also fine.

I have a mildly parallel concern about cluttering up developer machines, but a) storage is cheap, b) most won't be generating as much waste as we are, and c) it's easy to clean. Closing this is fine, and I'll work on the runner image.

**Comment by jhheider** [comment]
Resolved on https://github.com/teaxyz/infuser/commit/edc51fde3560c7bcb07945e567d60196ba6a0a4f

**Pull request closed without merging**
