### PR TITLE
fix(fixup): verify yaml key for `skip`: fix-patchelf and  fix-machos

### PR DESCRIPTION
**Pull request by tsirysndr**
fixes https://github.com/pkgxdev/pantry/pull/3724

### CODE REVIEW

**Comment by jhheider** [comment]
Definitely need to make all the formatting changes in a different branch if desired.

We should probably have a yaml key for skip-patchelf and skip-fix-machos.

**Comment by tsirysndr** [comment]
I've added a check of the new yaml keys `skip-patchelf` and `skip-fix-machos`

**Comment by jhheider** [comment]
I love it. Moves it to the yaml. Any concerns, @mxcl?

**Comment by mxcl** [comment]
Why are we skipping? I prefer to fix the problem than work around it. If possible.

**Comment by jhheider** [comment]
deno-built binaries can't have fix-elf.ts run on them, or it breaks the DATA segment look up, and they just become bloated deno binaries. it would let us generalize:
https://github.com/pkgxdev/brewkit/blob/a9c140eec89c8a9db429c5c2ffb2c2b03198bbf3/share/brewkit/fix-elf.ts#L26-L34

and give us a path when similar issues are found in the fix-machos.rb side.

**Comment by mxcl** [comment]
Agreed, though I was looking for explanation for this pacakge? Does it use `deno`?

I think a more suitable syntax here would be `skip: [fix-macho, fix-patchelf]`

And we can do even better for v2 with some kind of composable build steps system.

**Comment by jhheider** [comment]
yup, deno. this is our third, but surely far from our last. your skip `string | string[]` is more forward looking, and i like it.

**Comment by mxcl** [comment]
I wonder if these other deno packages had the same problem as we did packaging for homebrew core?

**Review by mxcl — APPROVED** [review]
lgtm! many thanks for a great patch

**Comment by jhheider** [comment]
re: that test failure: I don't know where we're finding that pip tag. I think it must have been deleted, but the api is still serving it.

https://github.com/pypa/pip/tags

**Comment by mxcl** [comment]
Crossing fingers that the build failure is nothing to do with this since it seems impossible it was.

**Pull request merged**
