### PR TITLE
feat(usePantry): Add support for multiple dists in `distributable`.

### PR DESCRIPTION
**Pull request by isworking**
The same as #196

### CODE REVIEW

**Comment by mxcl** [comment]
I added a fixture and it appears to fail, I guess we need to wrap the new fetch code.

**Comment by isworking** [comment]
> I added a fixture and it appears to fail, I guess we need to wrap the new fetch code.

It checks and tries to find the first working URL. For invalid URLs, it's supposed to fail.

**Comment by isworking** [comment]
Maybe `cscope` one would be a good example:
```yml
distributable:
    - url: https://downloads.sourceforge.net/project/cscope/cscope/v{{version.raw}}/cscope-{{version.raw}}.tar.gz
      strip-components: 1
    - url: https://downloads.sourceforge.net/project/cscope/cscope/v{{version.raw}}/cscope-{{version.raw}}.tar.bz2
      strip-components: 1
```

**Comment by isworking** [comment]
Okay, I misunderstood the fixture. I've added a `catch` block to handle exceptions as well

**Comment by isworking** [comment]
And thus it passes that test. Sorry for the delay

**Comment by mxcl** [comment]
Tremendous, thanks for the work.

**Pull request merged**
