### PR TITLE
Fixes https://github.com/teaxyz/pantry.core/issues/173

### PR DESCRIPTION
**Pull request by mxcl**
@jhheider you think this will work? Writing tests is a little much RN.

### CODE REVIEW

**Review by jhheider — APPROVED** [review]
That looks right.

**Comment by jhheider** [comment]
building openssl-1.1.1s should show it (and can be done by new-versioning against this branch)

**Comment by mxcl** [comment]
> and can be done by new-versioning against this branch

yeah well, we can’t now since this is a separate repo. We'll need to add tests here.

**Comment by jhheider** [comment]
Urk. Right. Right.

**Pull request merged**
