### PR TITLE
Fix `bk docker` and `bk edit`

### PR DESCRIPTION
**Pull request by felipecrs**
Refs https://github.com/pkgxdev/pantry/pull/5472#issuecomment-1984783935
Refs https://github.com/pkgxdev/brewkit/issues/316

### CODE REVIEW

**Comment by jhheider** [comment]
looks like https://github.com/pkgxdev/brewkit/pull/314; thought i'd searched for others, but everything (seemed) to work. we should double-check this is the last one.

**Comment by felipecrs** [comment]
Good point. I fixed bk-edit (which I had spotted in https://github.com/pkgxdev/brewkit/issues/316), and that was the last shell script with such a reference.

But if you search for `../..` you can find some other references in `ts` files. I would suggest you give it a search yourself, as I'm not as familiar as you with this code base.

There's this one for example:

https://github.com/felipecrs/brewkit/blob/031b62dfe41d4aedd6a8e8e2cbd1370d97d87384/lib/porcelain/fix-up.ts#L15

**Comment by jhheider** [comment]
Looking through, bk-edit and bk-docker look like the only ones. The .ts files are all clearly working, but the bk-_command_ files are half for end-users. I think those are the only two.

**Comment by mxcl** [comment]
I thought we'd already had this fix. Apparently not?

Or possibly the “fix” was the opposite.

I must have an oldish version of brewkit installed or something as I’ve been using both these commands without trouble.

**Comment by jhheider** [comment]
I think I missed these when I fixed `bk-init` for an issue. Hopefully, we've found them all now.

**Pull request merged**
