### PR TITLE
move all actions to `brewkit`

### PR DESCRIPTION
**Pull request by jhheider**
Moves all CI/CD/build actions to `teaxyz/brewkit`

works with https://github.com/teaxyz/pantry.core/pull/546 and https://github.com/teaxyz/pantry.extra/pull/493

- [x] update `@move-actions` to ~`@main`~ `@v0` before merge

full test: https://github.com/teaxyz/pantry.core/actions/runs/4380507625

### CODE REVIEW

**Comment by mxcl** [comment]
`actions` can be top-level IMO, since they are now a purpose of the repo rather than being infra inside the pantry

**Comment by mxcl** [comment]
> requires https://github.com/teaxyz/pantry.core/pull/546 and https://github.com/teaxyz/pantry.extra/pull/493

strictly no, right? Those PRs depend on this. This does not depend on those.

---

One thing: we’ll need `@v0` tags so that we can prevent revlock

**Comment by mxcl** [comment]
the vxtagger workflow I use with tea/cli seems reliable

**Comment by jhheider** [comment]
- [x] moved actions to top level
- [x] changed references to `@v0`
- [x] added `workflows/retagger.yml`
- [x] moved `.github/scripts/utils` to `libexec/utils` (willing to hear argument for other locations)

**Comment by jhheider** [comment]
my life is filled with never-ending wonder since I'm always surprised when software does what was intended.

but this seems to have worked.

**Pull request merged**
