### PR TITLE
Fixes #303

### LINKED ISSUE #303: successive linux builds fail to instantiate toolchain
at least in our docker image; possibly elsewhere:
```shell
pkgx $ bk b yarnpkg.com=3.8
env +git-scm.org +pkgx.sh/brewkit^0,^1
env -git-scm.org -pkgx.sh/brewkit^0,^1
  
  computing configuration
pkg: yarnpkg.com=3.8.0
src: /work/srcs/yarnpkg.com-3.8.0
build: /work/builds/yarnpkg.com-3.8.0
home: /work/homes/yarnpkg.com-3.8.0
install: ~/.pkgx/yarnpkg.com/v3.8.0
build-install: ~/.pkgx/yarnpkg.com/v3.8.0+brewing
  
  fetch & extract
  
  stage
rsync /work/projects/yarnpkg.com /work/builds/yarnpkg.com-3.8.0/props
error: Uncaught (in promise) AlreadyExists: File exists (os error 17): symlink '/root/.pkgx/llvm.org/v*/bin/clang' -> '/work/homes/yarnpkg.com-3.8.0/toolchain/cc'
    Deno.symlinkSync(target.string, this.string)
         ^
    at Object.symlinkSync (ext:deno_fs/30_fs.js:541:3)
    at Path.ln (https://deno.land/x/libpkgx@v0.17.0/src/utils/Path.ts:377:10)
    at symlink (file:///root/.pkgx/pkgx.sh/brewkit/v1.12.0/bin/cmd/build:178:14)
    at make_toolchain (file:///root/.pkgx/pkgx.sh/brewkit/v1.12.0/bin/cmd/build:182:5)
    at file:///root/.pkgx/pkgx.sh/brewkit/v1.12.0/bin/cmd/build:84:24
    at eventLoopTick (ext:core/01_core.js:182:7)
```

currently, `rm -rf homes/yarnpkg.com=3.8.0 && bk b yarnpkg.com=3.8` works as a workaround.

### PR DESCRIPTION
**Pull request by mxcl**

### CODE REVIEW

**Comment by mxcl** [comment]
don't get it

```
error: Uncaught (in promise) AlreadyExists: File exists (os error 17): symlink '/home/runner/.pkgx/llvm.org/v*/bin/clang' -> '/home/runner/work/brewkit/brewkit/homes/stark.com__foo-1.13.0/toolchain/cc'
    Deno.symlinkSync(target.string, this.string)
```

**Comment by jhheider** [comment]
add `.rm()` to `const d = config.path.home.join('toolchain').mkdir('p')` probably.

**Comment by jhheider** [comment]
or you can make Path.ln() do .rm() automatically, but that feels a little too magical.

**Comment by mxcl** [comment]
Path.ts has the attitude of “if the thing you want to do is already done it’s a noop” so it fits. But not willing to bump libpkgx to fix the issue here.

Monorepos have advantages.

**Comment by jhheider** [comment]
i think that's probably often true in path management. but, and maybe you feel differently, i _expect_ `cp`/`mv`/`ln` to overwrite by default (and get irrationally upset when `ln` doesn't and complains). so, something to consider in the interface design.

if `Deno.symlinkSync()` had a `force` option, that'd be the obvious bit to expose. _we_ could add a `force` option to `ln()`, but that'd just be chaining in a `.rm()`.

**Pull request merged**
