### PR TITLE
don't output `~` for empty srcs

### PR DESCRIPTION
**Pull request by jhheider**
I believe this to be a regression. See: https://github.com/teaxyz/pantry.core/actions/runs/4316867792/jobs/7533236794

### CODE REVIEW

**Comment by jhheider** [comment]
Actually, I think this is still a regression, but I believe we should be using `srcs-relative-paths`, so we can regress if we want.

**Comment by jhheider** [comment]
https://github.com/teaxyz/pantry.core/commit/04cd68f914114875f3d884ce5e27a4ca25a42b9a restores functionality. Regress if desired.

**Comment by mxcl** [comment]
Outputting ~ was necessary since we had to provide the same number of sources, bottles, signatures etc. to one of the other actions.

Thus it even’d up the numbers if there was no sources for a package.

So this is not a regression. Perhaps we no longer need it though and you would still prefer to remove it?

**Comment by jhheider** [comment]
At some point, we can audit which outputs we're still using, but at this time, the bug exposed has been squashed by not using the absolute variant.

We rebuild packages without srcs (tea.xyz/gx/cc and curl.se/ca-certs) so infrequently this could have been broken for a _while_.

**Comment by mxcl** [comment]
I hate that we have these special cases and almost made it so you *must* have a distributable, even if it's `example.com/fixture.tgz` or some fixture we can provide ourselves. It would have prevented a few bugs now at the expense of some weirdness in a minority of yamls.

**Pull request closed without merging**
